In [1]:
import numpy as np

In [2]:
#Arrays
a = np.array([1, 2, 3])
print(type(a),a.shape,a[0],a[1],a[2])
a[0] = 5         
print("a:",a)
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print("b:",b)


<class 'numpy.ndarray'> (3,) 1 2 3
a: [5 2 3]
b: [[1 2 3]
 [4 5 6]]


In [3]:
#create arrays
a = np.zeros((2,2))
print("a:",a)
b = np.ones((1,2))
print("b:",b)
c = np.full((2,2), 7)
print("c:",c)
d = np.eye(2)
print("d:",d)
e = np.random.random((2,2))
print("e:",e)

a: [[0. 0.]
 [0. 0.]]
b: [[1. 1.]]
c: [[7 7]
 [7 7]]
d: [[1. 0.]
 [0. 1.]]
e: [[0.69945087 0.86649329]
 [0.22156139 0.05478786]]


In [4]:
#Array indexing
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print("Sliced a array: ",b)

Sliced a array:  [[2 3]
 [6 7]]


In [5]:
print(a[0, 1])
b[0, 0] = 77
print(a[0, 1])
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

2
77
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
row_r1 = a[1,:]      
row_r2 = a[1:2,:]  
row_r3 = a[[1],:]  
print(row_r1,row_r1.shape)
print(row_r2,row_r2.shape)
print(row_r3,row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [10]:
col_r1 = a[:,1]
col_r2 = a[:,1:2]
print(col_r1,col_r1.shape)
print(col_r2,col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [11]:
a = np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]])
print(np.array([a[0,0],a[1,1],a[2,0]]))
print(a[[0,0],[1,1]])
print(np.array([a[0,1],a[0,1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [13]:
#Datatypes
x = np.array([1,2])
y = np.array([1.0,2.0])
z = np.array([1,2], dtype=np.int64)
print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


In [16]:
#Array math
x = np.array([[1,2],[3,4]],dtype=np.float64)
y = np.array([[5,6],[7,8]],dtype=np.float64)
print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))

[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [17]:
v = np.array([9,10])
w = np.array([11,12])
print(np.dot(v,w)) #or use print(v @ w)
print(np.dot(x,v))
print(np.dot(x,y))


219
[29. 67.]
[[19. 22.]
 [43. 50.]]


In [18]:
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1)) 

10.0
[4. 6.]
[3. 7.]


In [20]:
print("transpose:", x.T)

transpose: [[1. 3.]
 [2. 4.]]


In [21]:
#Broadcasting
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)
for i in range(4):
    y[i, :] = x[i, :] + v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [23]:
#Stacking
vv = np.tile(v,(4,1))
print(vv)
y = x + vv
print(y)
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10, 11, 12]])
v = np.array([1,0,1])
y = x + v
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [24]:
v = np.array([1,2,3])
w = np.array([4,5])
print(np.reshape(v,(3, 1))*w)
x = np.array([[1,2,3],[4,5,6]])
print(x+v)
print((x.T+w).T)
print(x+np.reshape(w,(2,1)))

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
